import React, { createContext, useContext, useEffect, useState, ReactNode } from 'react';
import { NativeModules, Platform } from 'react-native';
import { Dhikr, Language } from '@/types';
import { DHIKR_I18N } from '@/data/dhikr-i18n';
import { getDhikrTransliteration } from '@/lib/dhikr-transliteration';
import { getStoredLanguage, setStoredLanguage, hasSelectedLanguage as checkStoredLanguage } from '@/lib/storage';
import { SUPPORTED_LANGUAGES } from '@/lib/languages';

export { getDhikrTransliteration } from '@/lib/dhikr-transliteration';

export type { Language } from '@/types';

const SUPPORTED: Language[] = SUPPORTED_LANGUAGES;

export function getDhikrTitle(dhikr: Dhikr, language: Language): string {
  switch (language) {
    case 'en':
      return dhikr.titleEn ?? '';
    case 'ru':
      return dhikr.titleRu ?? '';
    case 'ar':
      return dhikr.titleAr ?? '';
    case 'kk':
      return dhikr.titleRu ?? dhikr.titleEn ?? dhikr.title;
    case 'tr':
    default:
      return dhikr.title;
  }
}

export function getDhikrMeaning(dhikr: Dhikr, language: Language): string {
  return DHIKR_I18N[dhikr.id]?.[language]?.meaning ?? '';
}

export function getDhikrExplanation(dhikr: Dhikr, language: Language): string {
  return DHIKR_I18N[dhikr.id]?.[language]?.explanation ?? '';
}

export function getDhikrSearchText(dhikr: Dhikr, language: Language): string {
  const meaning = getDhikrMeaning(dhikr, language);
  return [
    getDhikrTitle(dhikr, language),
    getDhikrTransliteration(dhikr, language),
    meaning,
  ]
    .join(' ')
    .toLowerCase();
}

export { checkStoredLanguage as hasSelectedLanguage };

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => Promise<void>;
  t: (key: string) => string;
  isLoading: boolean;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

const translations: Record<Language, Record<string, string>> = {
  tr: {
    // tabs
    tab_home: 'Ana Sayfa',
    tab_dhikr: 'Zikir',
    tab_tesbihim: 'Tesbihim',
    tab_programs: 'Programlar',
    tab_statistics: 'İstatistik',
    tab_premium: 'Premium',

    // home
    home_tagline: 'Niyetini Kur. Yolculuğunu Takip Et.',
    home_daily_inspiration: 'Günlük İlham',
    home_continue_dhikr: 'Zikreye Devam Et',
    home_categories: 'Kategoriler',
    home_see_all: 'Tümünü Gör',
    home_featured_programs: 'Öne Çıkan Programlar',
    home_popular_dhikr: 'Popüler Zikirler',

    // categories / dhikr list
    dhikr_library: 'Zikir Kütüphanesi',
    search_placeholder: 'Zikir veya dua ara...',
    cat_all: 'Tümü',
    browse_by_category: 'Kategoriye Göre Gez',
    all_dhikr: 'Tüm Zikirler',
    results_for: 'Sonuçlar:',
    items: 'adet',
    no_results: 'Sonuç Bulunamadı',
    no_results_desc: 'Farklı bir arama terimi veya kategori deneyin',

    // dhikr detail
    meaning: 'Anlam',
    explanation: 'Açıklama ve Faziletler',
    session_progress: 'Oturum İlerlemesi',
    target_count: 'Hedef Sayı',
    start_dhikr: 'Zikre Başla',
    resume: 'Devam Et',
    dhikr_not_found: 'Zikir bulunamadı',

    // counter
    tap_to_count: 'say',
    tap_label: 'ZİKİR',
    tap_sublabel: 'DOKUN',
    completed_msg: 'Sübhanallah! Tamamlandı!',
    completed_sub: 'Zikriniz kaydedildi',
    of: '/',

    // programs
    spiritual_programs: 'Manevi Programlar',
    programs_subtitle: 'Kalıcı alışkanlıklar kazandıran yapılandırılmış yolculuklar',
    daily_tracker: 'Günlük Takip',
    view_tracker: 'Günlük Takibi Gör',
    begin_program: 'Programa Başla',
    unlock_premium: 'Premium ile Kilidi Aç',
    upgrade: 'Yükselt',
    programs_loading: 'Programlar Yükleniyor...',
    check_connection: 'Bağlantınızı kontrol edin',
    programs_coming_soon: 'Programlar Yakında',
    programs_coming_soon_desc: 'Günlük zikir programları ve manevi takip özellikleri çok yakında eklenecek.',
    day_label: 'Gün',
    days_label: 'Gün',
    program_progress: 'Program İlerlemesi',
    complete_day: 'Günü Tamamla',
    day_completed: 'Tamamlandı',
    mark_day_complete: 'Bu Günü Tamamlandı İşaretle',
    assigned_dhikr: 'Günün Zikirleri',
    program_not_found: 'Program bulunamadı',
    tap_to_begin: 'Yolculuğa başlamak için dokunun',
    days_complete: 'gün tamamlandı',
    continue_program: 'Programa Devam Et',
    overall_progress: 'Genel İlerleme',
    settings_title: 'Ayarlar',
    settings_language: 'Dil',
    settings_language_desc: 'Uygulama dilini değiştirin',
    settings_app: 'Uygulama',
    free_limit_notice: 'Kategori başına ilk 10 zikir ücretsiz',

    // statistics
    your_journey: 'Yolculuğunuz',
    track_progress: 'Manevi gelişiminizi takip edin',
    total_dhikr: 'Toplam Zikir',
    across_sessions: 'tüm oturumlarınız boyunca',
    today: 'Bugün',
    this_week: 'Bu Hafta',
    this_month: 'Bu Ay',
    all_time: 'Tüm Zamanlar',
    dhikr_count: 'Zikir Sayısı',
    completed: 'Tamamlanan',
    sessions_label: 'oturum',
    all_time_summary: 'Tüm Zamanlar Özeti',
    sessions_completed: 'Tamamlanan Oturumlar',
    active_sessions: 'Aktif Oturumlar',
    programs_enrolled: 'Kayıtlı Programlar',
    programs_finished: 'Tamamlanan Programlar',
    keep_going: 'Devam Et!',
    streak_desc: "Her zikir sizi Allah'a yaklaştırır. Kararlılığınız en büyük gücünüzdür.",
    recent_sessions: 'Son Oturumlar',

    // premium
    premium_title: 'ZIKR Premium',
    app_subtitle: 'Daily Dhikr & Dua',
    premium_subtitle: 'Her zikir, program ve içgörüye sınırsız erişimle manevi yolculuğunuzu derinleştirin.',
    what_you_get: 'Neler Alacaksınız',
    choose_plan: 'Plan Seçin',
    monthly: 'Aylık',
    yearly: 'Yıllık',
    plan_monthly_premium: 'Aylık Premium',
    plan_yearly_premium: 'Yıllık Premium',
    locked_dhikr_premium: 'Bu zikir Premium üyelere özeldir',
    premium_upgrade_btn: "Premium'a Geç",
    premium_label: 'Premium',
    error_load_data: 'Veriler yüklenemedi',
    goals_completed: 'Tamamlanan Hedefler',
    total_time: 'Toplam Süre',
    time_seconds: 'sn',
    time_minutes: 'dk',
    time_hours: 'sa',
    best_value: 'En İyi Değer',
    save_44: '%44 Tasarruf',
    unlock_premium_btn: "Premium'u Aç",
    per_month: '/ay',
    per_year: '/yıl',
    free_trial: '7 günlük ücretsiz deneme · İstediğiniz zaman iptal edin · App Store / Google Play üzerinden faturalandırılır',
    secure_payment: 'Güvenli ödeme',
    no_hidden_fees: 'Gizli ücret yok',
    auto_renew: 'Otomatik yenilenir',
    locked_preview: 'Kilitli İçerik Önizlemesi',
    feat_unlimited_dhikr: 'Sınırsız Zikir',
    feat_unlimited_dhikr_desc: 'Tam kütüphanemizdeki her zikir ve duaya limitsiz erişin.',
    feat_unlimited_programs: 'Sınırsız Program',
    feat_unlimited_programs_desc: 'Tüm manevi programlara ve çok günlük yolculuklara kaydolun.',
    feat_cloud_backup: 'Bulut Yedekleme',
    feat_cloud_backup_desc: 'İlerlemeniz tüm cihazlarınızda otomatik senkronize edilir.',
    feat_stats: 'Gelişmiş İstatistikler',
    feat_stats_desc: 'Manevi pratiğiniz ve zaman içindeki büyümeniz hakkında derin içgörüler.',
    locked_item_1: '30 Günlük Salavat Programı',
    locked_item_2: 'Bulut Senkronizasyonu',
    locked_item_3: 'Öncelikli Destek',

    // language selection
    select_language: 'Dil Seçin',
    select_language_desc: 'Devam etmeden önce dilinizi seçin',
    lang_turkish: 'Türkçe',
    lang_english: 'English',
    lang_arabic: 'العربية',
    lang_russian: 'Русский',
    continue: 'Devam Et',

    // categories
    cat_rizq: 'Rızık ve Bereket',
    cat_healing: 'Şifa',
    cat_peace: 'Huzur ve Sükunet',
    cat_protection: 'Korunma',
    cat_salawat: 'Salavatlar',
    cat_asma: 'Esmaül Hüsna',
    cat_relationships: 'İlişkiler ve Evlilik',
    cat_opportunities: 'Ev, İş ve Fırsatlar',
    tesbihim_title: 'Tesbihim',
    tesbihim_subtitle: 'Kişisel zikir sayacınız',
    tesbih_name: 'Zikir Adı',
    tesbih_name_placeholder: 'Örn: Subhanallah',
    tesbih_target: 'Hedef Sayı (isteğe bağlı)',
    tesbih_target_placeholder: '33, 99, 100...',
    tesbih_no_target: 'Hedefsiz',
    tesbih_create: 'Oluştur ve Başla',
    tesbih_empty: 'Henüz tesbih yok',
    tesbih_empty_desc: 'Yukarıdan yeni bir zikir oluşturun veya hazır seçenekleri kullanın',
    tesbih_quick: 'Hızlı Başlat',
    tesbih_my_list: 'Tesbihlerim',
    tesbih_delete: 'Sil',
    tesbih_delete_confirm: 'Bu tesbihi silmek istediğinize emin misiniz?',
    tesbih_back_to_list: 'Listeye Dön',
    tesbih_back: 'Geri',
    tesbih_reset: 'Sıfırla',
    tesbih_most_used: 'En çok kullanılan',
    most_used_dhikr: 'En Çok Kullanılan Zikir',
    tesbih_stats_title: 'Tesbihim İstatistikleri',
    tesbih_total: 'Toplam sayım',
    settings_version: 'Sürüm',
    settings_privacy: 'Gizlilik Politikası',
    settings_terms: 'Kullanım Koşulları',
    settings_haptics: 'Titreşim',
    settings_haptics_desc: 'Zikir sayacına dokunurken titreşim',
    settings_haptics_on: 'Açık',
    settings_haptics_off: 'Kapalı',
    settings_premium_test: 'Premium Test Modu',
    settings_premium_test_desc: 'Kilitli içerikleri test etmek için açın (geliştirme)',
    premium_active: 'Premium Aktif',
    premium_inactive: 'Ücretsiz Sürüm',
    premium_test_unlock: 'Test için Premium Aç',
    premium_test_lock: 'Premium Kapat',
    premium_subscribe_btn: 'Premium Abone Ol',
    premium_subscribed: 'Premium Aktif',
    premium_restore: 'Satın Alımları Geri Yükle',
    premium_restore_success: 'Premium aboneliğiniz geri yüklendi.',
    premium_restore_none: 'Geri yüklenecek aktif abonelik bulunamadı.',
    premium_restore_failed: 'Satın alımlar geri yüklenemedi.',
    premium_loading: 'Planlar yükleniyor...',
    purchase_cancelled: 'Satın alma iptal edildi.',
    purchase_failed: 'Satın alma başarısız oldu. Lütfen tekrar deneyin.',
    purchase_network_error: 'Ağ hatası. Bağlantınızı kontrol edin.',
    purchase_no_products: 'Abonelik planları bulunamadı.',
    purchase_not_available: 'Satın alma bu cihazda kullanılamıyor.',
    settings_subscription: 'Abonelik',
    settings_restore_purchases: 'Satın Alımları Geri Yükle',
    settings_manage_subscription: 'Aboneliği Yönet',
    lang_kazakh: 'Қазақша',
  },
  en: {
    tab_home: 'Home',
    tab_dhikr: 'Dhikr',
    tab_tesbihim: 'My Tasbih',
    tab_programs: 'Programs',
    tab_statistics: 'Statistics',
    tab_premium: 'Premium',
    home_tagline: 'Set Your Intention. Track Your Journey.',
    home_daily_inspiration: 'Daily Inspiration',
    home_continue_dhikr: 'Continue Dhikr',
    home_categories: 'Categories',
    home_see_all: 'See All',
    home_featured_programs: 'Featured Programs',
    home_popular_dhikr: 'Popular Dhikr',
    dhikr_library: 'Dhikr Library',
    search_placeholder: 'Search dhikr or dua...',
    cat_all: 'All',
    browse_by_category: 'Browse by Category',
    all_dhikr: 'All Dhikr',
    results_for: 'Results for',
    items: 'items',
    no_results: 'No Results Found',
    no_results_desc: 'Try a different search term or category',
    meaning: 'Meaning',
    explanation: 'Explanation & Virtues',
    session_progress: 'Session Progress',
    target_count: 'Target Count',
    start_dhikr: 'Start Dhikr',
    resume: 'Resume',
    dhikr_not_found: 'Dhikr not found',
    tap_to_count: 'to count',
    tap_label: 'DHIKR',
    tap_sublabel: 'TAP',
    completed_sub: 'Your dhikr has been recorded',
    of: 'of',
    spiritual_programs: 'Spiritual Programs',
    programs_subtitle: 'Structured journeys to build lasting habits',
    daily_tracker: 'Daily Tracker',
    view_tracker: 'View Day Tracker',
    begin_program: 'Begin Program',
    unlock_premium: 'Unlock with Premium',
    upgrade: 'Upgrade',
    programs_loading: 'Programs Loading...',
    check_connection: 'Check your connection',
    programs_coming_soon: 'Programs Coming Soon',
    programs_coming_soon_desc: 'Daily dhikr programs and spiritual tracking features are coming soon.',
    day_label: 'Day',
    days_label: 'Days',
    program_progress: 'Program Progress',
    complete_day: 'Complete Day',
    day_completed: 'Completed',
    mark_day_complete: 'Mark This Day Complete',
    assigned_dhikr: "Today's Dhikr",
    program_not_found: 'Program not found',
    tap_to_begin: 'Tap to begin your journey',
    days_complete: 'days complete',
    continue_program: 'Continue Program',
    overall_progress: 'Overall Progress',
    settings_title: 'Settings',
    settings_language: 'Language',
    settings_language_desc: 'Change the app language',
    settings_app: 'App',
    free_limit_notice: 'First 10 dhikr per category are free',
    your_journey: 'Your Journey',
    track_progress: 'Track your spiritual progress',
    total_dhikr: 'Total Dhikr Recited',
    across_sessions: 'across all your sessions',
    today: 'Today',
    this_week: 'This Week',
    this_month: 'This Month',
    all_time: 'All Time',
    dhikr_count: 'Dhikr Count',
    completed: 'Completed',
    sessions_label: 'sessions',
    all_time_summary: 'All-Time Summary',
    sessions_completed: 'Sessions Completed',
    active_sessions: 'Active Sessions',
    programs_enrolled: 'Programs Enrolled',
    programs_finished: 'Programs Finished',
    keep_going: 'Keep Going!',
    streak_desc: 'Every dhikr brings you closer to Allah. Your consistency is your greatest strength.',
    recent_sessions: 'Recent Sessions',
    premium_title: 'ZIKR Premium',
    app_subtitle: 'Daily Dhikr & Dua',
    premium_subtitle: 'Deepen your spiritual journey with unlimited access to every dhikr, program, and insight.',
    what_you_get: 'What you get',
    choose_plan: 'Choose a Plan',
    completed_msg: 'Subhanallah! Completed!',
    monthly: 'Monthly',
    yearly: 'Yearly',
    plan_monthly_premium: 'Monthly Premium',
    plan_yearly_premium: 'Yearly Premium',
    locked_dhikr_premium: 'This dhikr is exclusive to Premium members',
    premium_upgrade_btn: 'Upgrade to Premium',
    premium_label: 'Premium',
    error_load_data: 'Could not load data',
    goals_completed: 'Goals Completed',
    total_time: 'Total Time',
    time_seconds: 'sec',
    time_minutes: 'min',
    time_hours: 'hr',
    best_value: 'Best Value',
    save_44: 'Save 44%',
    unlock_premium_btn: 'Unlock Premium',
    per_month: '/month',
    per_year: '/year',
    free_trial: '7-day free trial · Cancel anytime · Billed via App Store / Google Play',
    secure_payment: 'Secure payment',
    no_hidden_fees: 'No hidden fees',
    auto_renew: 'Renews automatically',
    locked_preview: 'Locked Content Preview',
    feat_unlimited_dhikr: 'Unlimited Dhikr',
    feat_unlimited_dhikr_desc: 'Access every dhikr and dua in our full library without limits.',
    feat_unlimited_programs: 'Unlimited Programs',
    feat_unlimited_programs_desc: 'Enroll in all spiritual programs and multi-day journeys.',
    feat_cloud_backup: 'Cloud Backup',
    feat_cloud_backup_desc: 'Your progress syncs across all devices automatically.',
    feat_stats: 'Advanced Statistics',
    feat_stats_desc: 'Deep insights into your spiritual practice and growth over time.',
    locked_item_1: '30-Day Salawat Challenge',
    locked_item_2: 'Cloud Sync',
    locked_item_3: 'Priority Support',
    select_language: 'Select Language',
    select_language_desc: 'Choose your preferred language to continue',
    lang_turkish: 'Türkçe',
    lang_english: 'English',
    lang_arabic: 'العربية',
    lang_russian: 'Русский',
    continue: 'Continue',
    cat_rizq: 'Rizq & Abundance',
    cat_healing: 'Healing',
    cat_peace: 'Peace & Serenity',
    cat_protection: 'Protection',
    cat_salawat: 'Salawat',
    cat_asma: 'Asma Ul Husna',
    cat_relationships: 'Relationships & Marriage',
    cat_opportunities: 'Home, Work & Opportunities',
    tesbihim_title: 'My Tasbih',
    tesbihim_subtitle: 'Your personal dhikr counter',
    tesbih_name: 'Dhikr Name',
    tesbih_name_placeholder: 'e.g. Subhanallah',
    tesbih_target: 'Target Count (optional)',
    tesbih_target_placeholder: '33, 99, 100...',
    tesbih_no_target: 'No target',
    tesbih_create: 'Create & Start',
    tesbih_empty: 'No tasbih yet',
    tesbih_empty_desc: 'Create a new dhikr above or use quick presets',
    tesbih_quick: 'Quick Start',
    tesbih_my_list: 'My Tasbih',
    tesbih_delete: 'Delete',
    tesbih_delete_confirm: 'Are you sure you want to delete this tasbih?',
    tesbih_back_to_list: 'Back to List',
    tesbih_back: 'Back',
    tesbih_reset: 'Reset',
    tesbih_most_used: 'Most used',
    most_used_dhikr: 'Most Used Dhikr',
    tesbih_stats_title: 'My Tasbih Statistics',
    tesbih_total: 'Total count',
    settings_version: 'Version',
    settings_privacy: 'Privacy Policy',
    settings_terms: 'Terms of Use',
    settings_haptics: 'Vibration',
    settings_haptics_desc: 'Haptic feedback when tapping the dhikr counter',
    settings_haptics_on: 'On',
    settings_haptics_off: 'Off',
    settings_premium_test: 'Premium Test Mode',
    settings_premium_test_desc: 'Enable to test locked content (development)',
    premium_active: 'Premium Active',
    premium_inactive: 'Free Version',
    premium_test_unlock: 'Enable Premium for Testing',
    premium_test_lock: 'Disable Premium',
    premium_subscribe_btn: 'Subscribe to Premium',
    premium_subscribed: 'Premium Active',
    premium_restore: 'Restore Purchases',
    premium_restore_success: 'Your Premium subscription was restored.',
    premium_restore_none: 'No active subscription found to restore.',
    premium_restore_failed: 'Could not restore purchases.',
    premium_loading: 'Loading plans...',
    purchase_cancelled: 'Purchase was cancelled.',
    purchase_failed: 'Purchase failed. Please try again.',
    purchase_network_error: 'Network error. Check your connection.',
    purchase_no_products: 'Subscription plans not found.',
    purchase_not_available: 'Purchases are not available on this device.',
    settings_subscription: 'Subscription',
    settings_restore_purchases: 'Restore Purchases',
    settings_manage_subscription: 'Manage Subscription',
    lang_kazakh: 'Қазақша',
  },
  ar: {
    tab_home: 'الرئيسية',
    tab_dhikr: 'الذكر',
    tab_tesbihim: 'تسبيحي',
    tab_programs: 'البرامج',
    tab_statistics: 'الإحصاء',
    tab_premium: 'بريميوم',
    home_tagline: 'ضع نيتك. تابع رحلتك.',
    home_daily_inspiration: 'إلهام اليوم',
    home_continue_dhikr: 'متابعة الذكر',
    home_categories: 'الفئات',
    home_see_all: 'عرض الكل',
    home_featured_programs: 'البرامج المميزة',
    home_popular_dhikr: 'الأذكار الشائعة',
    dhikr_library: 'مكتبة الأذكار',
    search_placeholder: 'ابحث عن ذكر أو دعاء...',
    cat_all: 'الكل',
    browse_by_category: 'تصفح حسب الفئة',
    all_dhikr: 'جميع الأذكار',
    results_for: 'نتائج:',
    items: 'عنصر',
    no_results: 'لا توجد نتائج',
    no_results_desc: 'جرب كلمة بحث أو فئة مختلفة',
    meaning: 'المعنى',
    explanation: 'الشرح والفضائل',
    session_progress: 'تقدم الجلسة',
    target_count: 'العدد المستهدف',
    start_dhikr: 'ابدأ الذكر',
    resume: 'استكمال',
    dhikr_not_found: 'الذكر غير موجود',
    tap_to_count: 'للعدّ',
    tap_label: 'ذِكر',
    tap_sublabel: 'اضغط',
    completed_sub: 'تم تسجيل ذكرك',
    of: 'من',
    spiritual_programs: 'البرامج الروحية',
    programs_subtitle: 'رحلات منظمة لبناء عادات دائمة',
    daily_tracker: 'المتابعة اليومية',
    view_tracker: 'عرض المتابعة اليومية',
    begin_program: 'ابدأ البرنامج',
    unlock_premium: 'افتح بالبريميوم',
    upgrade: 'ترقية',
    programs_loading: 'جارٍ تحميل البرامج...',
    check_connection: 'تحقق من اتصالك',
    programs_coming_soon: 'البرامج قادمة قريباً',
    programs_coming_soon_desc: 'برامج الذكر اليومية وميزات التتبع الروحي ستتوفر قريباً.',
    day_label: 'يوم',
    days_label: 'أيام',
    program_progress: 'تقدم البرنامج',
    complete_day: 'إكمال اليوم',
    day_completed: 'مكتمل',
    mark_day_complete: 'تحديد هذا اليوم كمكتمل',
    assigned_dhikr: 'أذكار اليوم',
    program_not_found: 'البرنامج غير موجود',
    tap_to_begin: 'اضغط لبدء رحلتك',
    days_complete: 'أيام مكتملة',
    continue_program: 'متابعة البرنامج',
    overall_progress: 'التقدم العام',
    settings_title: 'الإعدادات',
    settings_language: 'اللغة',
    settings_language_desc: 'تغيير لغة التطبيق',
    settings_app: 'التطبيق',
    free_limit_notice: 'أول 10 أذكار في كل فئة مجانية',
    your_journey: 'رحلتك',
    track_progress: 'تتبع تقدمك الروحي',
    total_dhikr: 'إجمالي الأذكار',
    across_sessions: 'عبر جميع جلساتك',
    today: 'اليوم',
    this_week: 'هذا الأسبوع',
    this_month: 'هذا الشهر',
    all_time: 'كل الوقت',
    dhikr_count: 'عدد الأذكار',
    completed: 'مكتمل',
    sessions_label: 'جلسات',
    all_time_summary: 'ملخص كل الوقت',
    sessions_completed: 'الجلسات المكتملة',
    active_sessions: 'الجلسات النشطة',
    programs_enrolled: 'البرامج المسجلة',
    programs_finished: 'البرامج المنتهية',
    keep_going: 'واصل!',
    streak_desc: 'كل ذكر يقربك من الله. استمرارك هو أعظم قوتك.',
    recent_sessions: 'الجلسات الأخيرة',
    premium_title: 'ZIKR بريميوم',
    app_subtitle: 'الذكر والدعاء اليومي',
    premium_subtitle: 'عمّق رحلتك الروحية بوصول غير محدود لكل الأذكار والبرامج.',
    what_you_get: 'ماذا ستحصل عليه',
    choose_plan: 'اختر خطة',
    completed_msg: 'سبحان الله! اكتمل!',
    monthly: 'شهري',
    yearly: 'سنوي',
    plan_monthly_premium: 'بريميوم شهري',
    plan_yearly_premium: 'بريميوم سنوي',
    locked_dhikr_premium: 'هذا الذكر حصري لأعضاء بريميوم',
    premium_upgrade_btn: 'الترقية إلى بريميوم',
    premium_label: 'بريميوم',
    error_load_data: 'تعذر تحميل البيانات',
    goals_completed: 'الأهداف المكتملة',
    total_time: 'الوقت الإجمالي',
    time_seconds: 'ث',
    time_minutes: 'د',
    time_hours: 'س',
    best_value: 'أفضل قيمة',
    save_44: 'وفر 44%',
    unlock_premium_btn: 'افتح بريميوم',
    per_month: '/شهر',
    per_year: '/سنة',
    free_trial: '7 أيام مجانية · إلغاء في أي وقت · يُحسب عبر App Store / Google Play',
    secure_payment: 'دفع آمن',
    no_hidden_fees: 'لا رسوم خفية',
    auto_renew: 'يتجدد تلقائياً',
    locked_preview: 'معاينة المحتوى المقفل',
    feat_unlimited_dhikr: 'أذكار غير محدودة',
    feat_unlimited_dhikr_desc: 'الوصول لكل الأذكار والأدعية بدون حدود.',
    feat_unlimited_programs: 'برامج غير محدودة',
    feat_unlimited_programs_desc: 'التسجيل في جميع البرامج الروحية والرحلات متعددة الأيام.',
    feat_cloud_backup: 'النسخ الاحتياطي السحابي',
    feat_cloud_backup_desc: 'تقدمك يتزامن تلقائياً على جميع أجهزتك.',
    feat_stats: 'إحصاءات متقدمة',
    feat_stats_desc: 'رؤى عميقة حول ممارستك الروحية ونموك عبر الزمن.',
    locked_item_1: 'تحدي الصلاة على النبي 30 يوماً',
    locked_item_2: 'مزامنة سحابية',
    locked_item_3: 'دعم أولوية',
    select_language: 'اختر اللغة',
    select_language_desc: 'اختر لغتك المفضلة للمتابعة',
    lang_turkish: 'Türkçe',
    lang_english: 'English',
    lang_arabic: 'العربية',
    lang_russian: 'Русский',
    continue: 'متابعة',
    cat_rizq: 'الرزق والبركة',
    cat_healing: 'الشفاء',
    cat_peace: 'السكينة والطمأنينة',
    cat_protection: 'الحفظ والحماية',
    cat_salawat: 'الصلاة على النبي',
    cat_asma: 'الأسماء الحسنى',
    cat_relationships: 'الزواج والعلاقات',
    cat_opportunities: 'البيت والعمل والفرص',
    tesbihim_title: 'تسبيحي',
    tesbihim_subtitle: 'عداد الذكر الشخصي',
    tesbih_name: 'اسم الذكر',
    tesbih_name_placeholder: 'مثال: سبحان الله',
    tesbih_target: 'العدد المستهدف (اختياري)',
    tesbih_target_placeholder: '33، 99، 100...',
    tesbih_no_target: 'بدون هدف',
    tesbih_create: 'إنشاء وبدء',
    tesbih_empty: 'لا يوجد تسبيح بعد',
    tesbih_empty_desc: 'أنشئ ذكراً جديداً أو استخدم الاختيارات السريعة',
    tesbih_quick: 'بدء سريع',
    tesbih_my_list: 'تسبيحاتي',
    tesbih_delete: 'حذف',
    tesbih_delete_confirm: 'هل أنت متأكد من حذف هذا التسبيح؟',
    tesbih_back_to_list: 'العودة إلى القائمة',
    tesbih_back: 'رجوع',
    tesbih_reset: 'إعادة',
    tesbih_most_used: 'الأكثر استخداماً',
    most_used_dhikr: 'الذكر الأكثر استخداماً',
    tesbih_stats_title: 'إحصاءات تسبيحي',
    tesbih_total: 'إجمالي العد',
    settings_version: 'الإصدار',
    settings_privacy: 'سياسة الخصوصية',
    settings_terms: 'شروط الاستخدام',
    settings_haptics: 'الاهتزاز',
    settings_haptics_desc: 'اهتزاز عند الضغط على عداد الذكر',
    settings_haptics_on: 'مفعّل',
    settings_haptics_off: 'معطّل',
    settings_premium_test: 'وضع اختبار بريميوم',
    settings_premium_test_desc: 'فعّل لاختبار المحتوى المقفل (تطوير)',
    premium_active: 'بريميوم مفعّل',
    premium_inactive: 'النسخة المجانية',
    premium_test_unlock: 'تفعيل بريميوم للاختبار',
    premium_test_lock: 'إيقاف بريميوم',
    premium_subscribe_btn: 'اشترك في بريميوم',
    premium_subscribed: 'بريميوم مفعّل',
    premium_restore: 'استعادة المشتريات',
    premium_restore_success: 'تمت استعادة اشتراك بريميوم.',
    premium_restore_none: 'لم يتم العثور على اشتراك نشط.',
    premium_restore_failed: 'تعذرت استعادة المشتريات.',
    premium_loading: 'جاري تحميل الخطط...',
    purchase_cancelled: 'تم إلغاء الشراء.',
    purchase_failed: 'فشل الشراء. حاول مرة أخرى.',
    purchase_network_error: 'خطأ في الشبكة. تحقق من الاتصال.',
    purchase_no_products: 'لم يتم العثور على خطط الاشتراك.',
    purchase_not_available: 'الشراء غير متاح على هذا الجهاز.',
    settings_subscription: 'الاشتراك',
    settings_restore_purchases: 'استعادة المشتريات',
    settings_manage_subscription: 'إدارة الاشتراك',
    lang_kazakh: 'Қазақша',
  },
  ru: {
    tab_home: 'Главная',
    tab_dhikr: 'Зикр',
    tab_tesbihim: 'Мой тасбих',
    tab_programs: 'Программы',
    tab_statistics: 'Статистика',
    tab_premium: 'Премиум',
    home_tagline: 'Поставь намерение. Следи за путём.',
    home_daily_inspiration: 'Вдохновение дня',
    home_continue_dhikr: 'Продолжить зикр',
    home_categories: 'Категории',
    home_see_all: 'Смотреть все',
    home_featured_programs: 'Избранные программы',
    home_popular_dhikr: 'Популярные зикры',
    dhikr_library: 'Библиотека зикров',
    search_placeholder: 'Поиск зикра или дуа...',
    cat_all: 'Все',
    browse_by_category: 'По категориям',
    all_dhikr: 'Все зикры',
    results_for: 'Результаты:',
    items: 'элем.',
    no_results: 'Ничего не найдено',
    no_results_desc: 'Попробуйте другой запрос или категорию',
    meaning: 'Значение',
    explanation: 'Объяснение и достоинства',
    session_progress: 'Прогресс сессии',
    target_count: 'Целевое число',
    start_dhikr: 'Начать зикр',
    resume: 'Продолжить',
    dhikr_not_found: 'Зикр не найден',
    tap_to_count: 'нажмите',
    tap_label: 'ЗИКР',
    tap_sublabel: 'НАЖМИ',
    completed_sub: 'Ваш зикр записан',
    of: 'из',
    spiritual_programs: 'Духовные программы',
    programs_subtitle: 'Структурированные пути для формирования привычек',
    daily_tracker: 'Ежедневный трекер',
    view_tracker: 'Открыть трекер',
    begin_program: 'Начать программу',
    unlock_premium: 'Открыть с Премиум',
    upgrade: 'Улучшить',
    programs_loading: 'Загрузка программ...',
    check_connection: 'Проверьте подключение',
    programs_coming_soon: 'Программы скоро появятся',
    programs_coming_soon_desc: 'Ежедневные программы зикра и функции духовного отслеживания появятся совсем скоро.',
    day_label: 'День',
    days_label: 'Дней',
    program_progress: 'Прогресс программы',
    complete_day: 'Завершить день',
    day_completed: 'Завершено',
    mark_day_complete: 'Отметить день выполненным',
    assigned_dhikr: 'Зикры дня',
    program_not_found: 'Программа не найдена',
    tap_to_begin: 'Нажмите, чтобы начать путь',
    days_complete: 'дней завершено',
    continue_program: 'Продолжить программу',
    overall_progress: 'Общий прогресс',
    settings_title: 'Настройки',
    settings_language: 'Язык',
    settings_language_desc: 'Изменить язык приложения',
    settings_app: 'Приложение',
    free_limit_notice: 'Первые 10 зикров в каждой категории бесплатны',
    your_journey: 'Ваш путь',
    track_progress: 'Следите за духовным прогрессом',
    total_dhikr: 'Всего зикров',
    across_sessions: 'за все сессии',
    today: 'Сегодня',
    this_week: 'Эта неделя',
    this_month: 'Этот месяц',
    all_time: 'Всё время',
    dhikr_count: 'Количество зикров',
    completed: 'Завершено',
    sessions_label: 'сессий',
    all_time_summary: 'Итоги за всё время',
    sessions_completed: 'Завершённых сессий',
    active_sessions: 'Активных сессий',
    programs_enrolled: 'Программ записано',
    programs_finished: 'Программ завершено',
    keep_going: 'Продолжайте!',
    streak_desc: 'Каждый зикр приближает вас к Аллаху. Постоянство — ваша наибольшая сила.',
    recent_sessions: 'Последние сессии',
    premium_title: 'ZIKR Премиум',
    app_subtitle: 'Ежедневный зикр и дуа',
    premium_subtitle: 'Углубите духовный путь с неограниченным доступом ко всем зикрам и программам.',
    what_you_get: 'Что вы получаете',
    choose_plan: 'Выберите план',
    completed_msg: 'СубханаЛлах! Завершено!',
    monthly: 'Ежемесячно',
    yearly: 'Ежегодно',
    plan_monthly_premium: 'Премиум на месяц',
    plan_yearly_premium: 'Премиум на год',
    locked_dhikr_premium: 'Этот зикр доступен только участникам Премиум',
    premium_upgrade_btn: 'Перейти на Премиум',
    premium_label: 'Премиум',
    error_load_data: 'Не удалось загрузить данные',
    goals_completed: 'Выполненные цели',
    total_time: 'Общее время',
    time_seconds: 'сек',
    time_minutes: 'мин',
    time_hours: 'ч',
    best_value: 'Лучшая цена',
    save_44: 'Скидка 44%',
    unlock_premium_btn: 'Открыть Премиум',
    per_month: '/мес',
    per_year: '/год',
    free_trial: '7-дневный пробный период · Отмена в любое время · Оплата через App Store / Google Play',
    secure_payment: 'Безопасная оплата',
    no_hidden_fees: 'Без скрытых платежей',
    auto_renew: 'Автопродление',
    locked_preview: 'Заблокированный контент',
    feat_unlimited_dhikr: 'Безлимитные зикры',
    feat_unlimited_dhikr_desc: 'Доступ ко всем зикрам и дуа без ограничений.',
    feat_unlimited_programs: 'Безлимитные программы',
    feat_unlimited_programs_desc: 'Запись во все духовные программы и многодневные пути.',
    feat_cloud_backup: 'Облачное резервирование',
    feat_cloud_backup_desc: 'Ваш прогресс автоматически синхронизируется на всех устройствах.',
    feat_stats: 'Расширенная статистика',
    feat_stats_desc: 'Глубокий анализ духовной практики и роста с течением времени.',
    locked_item_1: '30-дневная программа Салавата',
    locked_item_2: 'Облачная синхронизация',
    locked_item_3: 'Приоритетная поддержка',
    select_language: 'Выберите язык',
    select_language_desc: 'Выберите предпочитаемый язык для продолжения',
    lang_turkish: 'Türkçe',
    lang_english: 'English',
    lang_arabic: 'العربية',
    lang_russian: 'Русский',
    continue: 'Продолжить',
    cat_rizq: 'Ризк и изобилие',
    cat_healing: 'Исцеление',
    cat_peace: 'Мир и покой',
    cat_protection: 'Защита',
    cat_salawat: 'Салават',
    cat_asma: 'Асмаул-Хусна',
    cat_relationships: 'Отношения и брак',
    cat_opportunities: 'Дом, работа и возможности',
    tesbihim_title: 'Мой тасбих',
    tesbihim_subtitle: 'Ваш личный счётчик зикра',
    tesbih_name: 'Название зикра',
    tesbih_name_placeholder: 'Напр: Субханаллах',
    tesbih_target: 'Целевое число (необязательно)',
    tesbih_target_placeholder: '33, 99, 100...',
    tesbih_no_target: 'Без цели',
    tesbih_create: 'Создать и начать',
    tesbih_empty: 'Тасбихов пока нет',
    tesbih_empty_desc: 'Создайте зикр выше или используйте быстрые варианты',
    tesbih_quick: 'Быстрый старт',
    tesbih_my_list: 'Мои тасбихи',
    tesbih_delete: 'Удалить',
    tesbih_delete_confirm: 'Удалить этот тасбих?',
    tesbih_back_to_list: 'К списку',
    tesbih_back: 'Назад',
    tesbih_reset: 'Сброс',
    tesbih_most_used: 'Самый используемый',
    most_used_dhikr: 'Самый используемый зикр',
    tesbih_stats_title: 'Статистика тасбиха',
    tesbih_total: 'Всего',
    settings_version: 'Версия',
    settings_privacy: 'Политика конфиденциальности',
    settings_terms: 'Условия использования',
    settings_haptics: 'Вибрация',
    settings_haptics_desc: 'Вибрация при нажатии на счётчик зикра',
    settings_haptics_on: 'Вкл',
    settings_haptics_off: 'Выкл',
    settings_premium_test: 'Тестовый режим Премиум',
    settings_premium_test_desc: 'Включите для проверки заблокированного контента',
    premium_active: 'Премиум активен',
    premium_inactive: 'Бесплатная версия',
    premium_test_unlock: 'Включить Премиум для теста',
    premium_test_lock: 'Отключить Премиум',
    premium_subscribe_btn: 'Подписаться на Премиум',
    premium_subscribed: 'Премиум активен',
    premium_restore: 'Восстановить покупки',
    premium_restore_success: 'Подписка Премиум восстановлена.',
    premium_restore_none: 'Активная подписка не найдена.',
    premium_restore_failed: 'Не удалось восстановить покупки.',
    premium_loading: 'Загрузка планов...',
    purchase_cancelled: 'Покупка отменена.',
    purchase_failed: 'Покупка не удалась. Попробуйте снова.',
    purchase_network_error: 'Ошибка сети. Проверьте подключение.',
    purchase_no_products: 'Планы подписки не найдены.',
    purchase_not_available: 'Покупки недоступны на этом устройстве.',
    settings_subscription: 'Подписка',
    settings_restore_purchases: 'Восстановить покупки',
    settings_manage_subscription: 'Управление подпиской',
    lang_kazakh: 'Қазақша',
  },
  kk: {
    tab_home: 'Басты бет',
    tab_dhikr: 'Зікір',
    tab_tesbihim: 'Тәсібіхім',
    tab_programs: 'Бағдарламалар',
    tab_statistics: 'Статистика',
    tab_premium: 'Премиум',
    home_tagline: 'Ниетіңізді қойыңыз. Жолыңызды бақылаңыз.',
    home_daily_inspiration: 'Күнделікті шабыт',
    home_continue_dhikr: 'Зікірді жалғастыру',
    home_categories: 'Санаттар',
    home_see_all: 'Барлығын көру',
    home_featured_programs: 'Ұсынылған бағдарламалар',
    home_popular_dhikr: 'Танымал зікірлер',
    dhikr_library: 'Зікір кітапханасы',
    search_placeholder: 'Зікір немесе дұға іздеу...',
    cat_all: 'Барлығы',
    browse_by_category: 'Санат бойынша шолу',
    all_dhikr: 'Барлық зікірлер',
    results_for: 'Нәтижелер:',
    items: 'дана',
    no_results: 'Нәтиже табылмады',
    no_results_desc: 'Басқа іздеу сөзі немесе санатты қолданып көріңіз',
    meaning: 'Мағынасы',
    explanation: 'Түсіндірме және қасиеттері',
    session_progress: 'Сессия прогрессі',
    target_count: 'Мақсатты саны',
    start_dhikr: 'Зікірді бастау',
    resume: 'Жалғастыру',
    dhikr_not_found: 'Зікір табылмады',
    tap_to_count: 'есептеу',
    tap_label: 'ЗІКІР',
    tap_sublabel: 'БАСЫҢЫЗ',
    completed_msg: 'Субханаллах! Аяқталды!',
    completed_sub: 'Зікіріңіз сақталды',
    of: '/',
    spiritual_programs: 'Рухани бағдарламалар',
    programs_subtitle: 'Тұрақты әдеттер қалыптастыруға арналған құрылымды жолдар',
    daily_tracker: 'Күнделікті бақылау',
    view_tracker: 'Күнделікті бақылауды көру',
    begin_program: 'Бағдарламаны бастау',
    unlock_premium: 'Премиуммен ашу',
    upgrade: 'Жаңарту',
    programs_loading: 'Бағдарламалар жүктелуде...',
    check_connection: 'Қосылымыңызды тексеріңіз',
    programs_coming_soon: 'Бағдарламалар жақында қосылады',
    programs_coming_soon_desc: 'Күнделікті зікір бағдарламалары мен рухани бақылау мүмкіндіктері жақында қосылады.',
    day_label: 'Күн',
    days_label: 'Күн',
    program_progress: 'Бағдарлама прогрессі',
    complete_day: 'Күнді аяқтау',
    day_completed: 'Аяқталды',
    mark_day_complete: 'Бұл күнді аяқталды деп белгілеу',
    assigned_dhikr: 'Күннің зікірлері',
    program_not_found: 'Бағдарлама табылмады',
    tap_to_begin: 'Жолға шығу үшін басыңыз',
    days_complete: 'күн аяқталды',
    continue_program: 'Бағдарламаны жалғастыру',
    overall_progress: 'Жалпы прогресс',
    settings_title: 'Параметрлер',
    settings_language: 'Тіл',
    settings_language_desc: 'Қолданба тілін өзгерту',
    settings_app: 'Қолданба',
    settings_version: 'Нұсқа',
    settings_privacy: 'Құпиялылық саясаты',
    settings_terms: 'Пайдалану шарттары',
    settings_haptics: 'Діріл',
    settings_haptics_desc: 'Зікір есебіне басқанда діріл',
    settings_haptics_on: 'Қосулы',
    settings_haptics_off: 'Өшірулі',
    settings_premium_test: 'Премиум сынақ режимі',
    settings_premium_test_desc: 'Құлыпталған мазмұнды тексеру үшін қосыңыз',
    premium_active: 'Премиум белсенді',
    premium_inactive: 'Тегін нұсқа',
    premium_test_unlock: 'Сынақ үшін Премиумды қосу',
    premium_test_lock: 'Премиумды өшіру',
    premium_subscribe_btn: 'Премиумға жазылу',
    premium_subscribed: 'Премиум белсенді',
    premium_restore: 'Сатып алуларды қалпына келтіру',
    premium_restore_success: 'Премиум жазылымы қалпына келтірілді.',
    premium_restore_none: 'Белсенді жазылым табылмады.',
    premium_restore_failed: 'Сатып алуларды қалпына келтіру сәтсіз аяқталды.',
    premium_loading: 'Жоспарлар жүктелуде...',
    purchase_cancelled: 'Сатып алу тоқтатылды.',
    purchase_failed: 'Сатып алу сәтсіз аяқталды. Қайта көріңіз.',
    purchase_network_error: 'Желі қатесі. Байланысты тексеріңіз.',
    purchase_no_products: 'Жазылым жоспарлары табылмады.',
    purchase_not_available: 'Бұл құрылғыда сатып алу қолжетімсіз.',
    settings_subscription: 'Жазылым',
    settings_restore_purchases: 'Сатып алуларды қалпына келтіру',
    settings_manage_subscription: 'Жазылымды басқару',
    free_limit_notice: 'Әр санаттағы алғашқы 10 зікір тегін',
    your_journey: 'Сіздің жолыңыз',
    track_progress: 'Рухани дамуыңызды бақылаңыз',
    total_dhikr: 'Жалпы зікір',
    across_sessions: 'барлық сессиялар бойынша',
    today: 'Бүгін',
    this_week: 'Осы апта',
    this_month: 'Осы ай',
    all_time: 'Барлық уақыт',
    dhikr_count: 'Зікір саны',
    completed: 'Аяқталған',
    sessions_label: 'сессия',
    all_time_summary: 'Барлық уақыт қорытындысы',
    sessions_completed: 'Аяқталған сессиялар',
    active_sessions: 'Белсенді сессиялар',
    programs_enrolled: 'Тіркелген бағдарламалар',
    programs_finished: 'Аяқталған бағдарламалар',
    keep_going: 'Жалғастырыңыз!',
    streak_desc: 'Әр зікір сізді Аллаға жақындатады. Тұрақтылығыңыз — ең үлкен күшіңіз.',
    recent_sessions: 'Соңғы сессиялар',
    premium_title: 'ZIKR Премиум',
    premium_subtitle: 'Әр зікір, бағдарлама және түсінікті шексіз қол жеткізумен рухани жолыңызды тереңдетіңіз.',
    app_subtitle: 'Күнделікті зікір және дұға',
    what_you_get: 'Не аласыз',
    choose_plan: 'Жоспарды таңдаңыз',
    monthly: 'Айлық',
    yearly: 'Жылдық',
    plan_monthly_premium: 'Айлық Премиум',
    plan_yearly_premium: 'Жылдық Премиум',
    locked_dhikr_premium: 'Бұл зікір Премиум мүшелерге арналған',
    premium_upgrade_btn: 'Премиумға өту',
    premium_label: 'Премиум',
    error_load_data: 'Деректер жүктелмеді',
    goals_completed: 'Орындалған мақсаттар',
    total_time: 'Жалпы уақыт',
    time_seconds: 'сек',
    time_minutes: 'мин',
    time_hours: 'сағ',
    best_value: 'Ең тиімді',
    save_44: '%44 үнемдеу',
    unlock_premium_btn: 'Премиумды ашу',
    per_month: '/ай',
    per_year: '/жыл',
    free_trial: '7 күн тегін сынақ · Кез келген уақытта бас тарту · App Store / Google Play арқылы төленеді',
    secure_payment: 'Қауіпсіз төлем',
    no_hidden_fees: 'Жасырын төлем жоқ',
    auto_renew: 'Автоматты жаңарту',
    locked_preview: 'Құлыпталған мазмұн алдын ала көрінісі',
    feat_unlimited_dhikr: 'Шексіз зікір',
    feat_unlimited_dhikr_desc: 'Толық кітапханадағы барлық зікір мен дұғаға шектеусіз қол жеткізіңіз.',
    feat_unlimited_programs: 'Шексіз бағдарламалар',
    feat_unlimited_programs_desc: 'Барлық рухани бағдарламаларға және көп күндік жолдарға тіркеліңіз.',
    feat_cloud_backup: 'Бұлттық сақтық көшірме',
    feat_cloud_backup_desc: 'Прогрессіңіз барлық құрылғыларда автоматты синхрондалады.',
    feat_stats: 'Кеңейтілген статистика',
    feat_stats_desc: 'Рухани тәжірибеңіз және уақыт өте келе өсуіңіз туралы терең түсініктер.',
    locked_item_1: '30 күндік Салауат бағдарламасы',
    locked_item_2: 'Бұлттық синхрондау',
    locked_item_3: 'Басымдықты қолдау',
    select_language: 'Тілді таңдаңыз',
    select_language_desc: 'Жалғастырмас бұрын тілді таңдаңыз',
    lang_turkish: 'Türkçe',
    lang_english: 'English',
    lang_arabic: 'العربية',
    lang_russian: 'Русский',
    lang_kazakh: 'Қазақша',
    continue: 'Жалғастыру',
    cat_rizq: 'Ризық пен береке',
    cat_healing: 'Шипа',
    cat_peace: 'Тыныштық пен жан тыныштығы',
    cat_protection: 'Қорғаныс',
    cat_salawat: 'Салауаттар',
    cat_asma: 'Алланың көркем есімдері',
    cat_relationships: 'Қарым-қатынас және неке',
    cat_opportunities: 'Үй, жұмыс және мүмкіндіктер',
    tesbihim_title: 'Тәсібіхім',
    tesbihim_subtitle: 'Жеке зікір санағышыңыз',
    tesbih_name: 'Зікір аты',
    tesbih_name_placeholder: 'Мыс: Субханаллах',
    tesbih_target: 'Мақсатты сан (міндетті емес)',
    tesbih_target_placeholder: '33, 99, 100...',
    tesbih_no_target: 'Мақсатсыз',
    tesbih_create: 'Жасау және бастау',
    tesbih_empty: 'Әлі тәсібіх жоқ',
    tesbih_empty_desc: 'Жоғарыдан жаңа зікір жасаңыз немесе дайын таңдауларды пайдаланыңыз',
    tesbih_quick: 'Жылдам бастау',
    tesbih_my_list: 'Тәсібіхтерім',
    tesbih_delete: 'Жою',
    tesbih_delete_confirm: 'Бұл тәсібіхті жойғыңыз келе ме?',
    tesbih_back_to_list: 'Тізімге оралу',
    tesbih_back: 'Артқа',
    tesbih_reset: 'Қайта',
    tesbih_most_used: 'Ең көп қолданылған',
    most_used_dhikr: 'Ең көп қолданылған зікір',
    tesbih_stats_title: 'Тәсібіх статистикасы',
    tesbih_total: 'Жалпы сан',
  },
};

function detectDeviceLanguage(): Language {
  try {
    let locale = 'tr';
    if (Platform.OS === 'ios') {
      locale =
        NativeModules.SettingsManager?.settings?.AppleLocale ||
        NativeModules.SettingsManager?.settings?.AppleLanguages?.[0] ||
        'tr';
    } else if (Platform.OS === 'android') {
      locale = NativeModules.I18nManager?.localeIdentifier || 'tr';
    }
    const code = locale.substring(0, 2).toLowerCase();
    if (code === 'tr') return 'tr';
    if (code === 'kk') return 'kk';
    if (code === 'ar') return 'ar';
    if (code === 'ru') return 'ru';
    if (code === 'en') return 'en';
  } catch {}
  return 'tr';
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLang] = useState<Language>('tr');
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    (async () => {
      try {
        const stored = await getStoredLanguage();
        if (stored && SUPPORTED.includes(stored as Language)) {
          setLang(stored as Language);
        } else {
          setLang(detectDeviceLanguage());
        }
      } catch {
        setLang(detectDeviceLanguage());
      } finally {
        setIsLoading(false);
      }
    })();
  }, []);

  const setLanguage = async (lang: Language) => {
    setLang(lang);
    try {
      await setStoredLanguage(lang);
    } catch {
      // ignore
    }
  };

  const t = (key: string): string => {
    return translations[language][key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isLoading }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function getTranslation(lang: Language, key: string): string {
  return translations[lang][key] ?? key;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used inside LanguageProvider');
  return ctx;
}

